### ISSUE TITLE
Unable to run pithos.io on my cassandra cluster

### ISSUE THREAD

**Issue by gayaks** [exoscale/pithos#172]
I was trying to run pithos.io on my cassandra cluster using the following command

java -jar pithos-0.7.5-standalone.jar -f etc/pithos/pithos.yaml

As per the stack trace, i am missing some configuration but not sure what i am missing as the documentation of pithos.io wasn't very much clear for me.

System Information

Cassandra Cluster version : 3.6 JRE version : 1.8

My pithos.yaml configuration as follows:

```
service:
   host: "0.0.0.0"
   port: 8080
logging:
   level: info
 console: true
  overrides:
    io.pithos: debug
options:
  service-uri: <hostname>
  default-region: myregion
keystore:
  keys:
    AKIAIOSFODNN7EXAMPLE:
      master: true
      tenant: test@example.com
      secret: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
bucketstore:
  default-region: myregion
  cluster: "10.21.46.94"
  keyspace: storage
regions:
  myregion:
    metastore:
      cluster : "10.21.46.94"
      keyspace: storage
    storage-classes:
      standard:
        cluster: "10.21.46.94"
        keyspace: storage
        max-chunk: "128k"
        max-block-chunk: 1024
cassandra:
   saved_caches_directory: "target/db/saved_caches"
   data_file_directories:
     - "target/db/data"
   commitlog_directory: "target/db/commitlog"
```
