### ISSUE TITLE
invalid log appender configuration 

### ISSUE THREAD

**Issue by dsehrawa** [exoscale/pithos#177]
Hi

I am getting following exception while trying to use rolling-file appender with pithos.

invalid or incomplete configuration:  clojure.lang.ExceptionInfo: invalid log appender configuration {:config {:appender :rolling-file, :rolling-policy "fixed-window", :file "/tmp/pithos1.log", :encoder #object[ch.qos.logback.classic.encoder.PatternLayoutEncoder 0x32ba5c65 "ch.qos.logback.classic.encoder.PatternLayoutEncoder@32ba5c65"], :pattern "%p [%d] %t - %c %m%n”}}

My pithos.yaml file is as below:

```
logging:
  level: info
  console: false
  files:
    - "/tmp/pithos.log"
  appenders:
    - appender: rolling-file
      rolling-policy: fixed-window
      file: "/tmp/pithos1.log"
      encoder: pattern
      pattern: "%p [%d] %t - %c %m%n"
  overrides:
    com.datastax: error
    io.pithos: debug
```

Can you please look into it ? Is there anything wrong with the way I configured the appender.

Thanks,
Dheeraj
