### ISSUE TITLE
Does pithos not support C* authentication?

### ISSUE THREAD

**Issue by ogg1e** [exoscale/pithos#68]
When trying to create the schema via:
```
java -jar pithos-0.7.4-standalone.jar -f pithos.yaml -a install-schema
```

I get the error:
```
main - io.pithos.config - invalid or incomplete configuration
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.6.71.203:9042: Host /10.6.71.203:9042 requires authentication, but no authenticator found in Cluster configuration
```

I'm using this in my yaml:
```
bucketstore:
  default-region: 'CH-GV1'
  cluster:
  - "10.6.71.202"
  - "10.6.71.203"
  - "10.6.71.206"
  keyspace: 'storage'
  username: 'pithos'
  password: 'pithos'

```

Is this the correct syntax for cluster config and username/passwords?  Is it not passing the username/password down to C*?
