### ISSUE TITLE
How do I configure Pithos to use a larger replication factor?

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#75]
I see from the code that Pithos should support specifying the replication strategy and factor, but it's not clear how this should be configured in the pithos.yml. Can you provide documentation or an example?

**Comment by phene** [comment]
@pyr - I could really use some advise here!

**Comment by phene** [comment]
Well, I finally got this working by adding:

```yaml
hints:
  replication:
    class: SimpleStrategy
    replication_factor: 2
```

to the `bucketstore` and `regions.xxx.storage-classes.standard` sections in the `pithos.yaml`
