### ISSUE TITLE
Internal Logging Does Not Respect Log Level

### ISSUE THREAD

**Issue by phene** [exoscale/pithos#84]
When configuring internal logging with the following in `/etc/pithos/pithos.yaml`:

```yaml
logging:
  level: warn
  files:
    - "/var/log/pithos/system.log"
  pattern: "%p [%d] %t - %c - %m%n"
```

and invoking with: `java -cp :/usr/lib/pithos/pithos.jar io.pithos -f /etc/pithos/pithos.yaml`

The target log file still receives info and debug messages.
